proxy:
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: admin
    password: admin
    groups: admins
  docker:
      internal-networking: true
  specs:
  - id: biodiversity_viewer
    display-name: Euler's number
    container-cmd: ["R", "-e", "shiny::runApp(appDir='/home/app')"]
    container-image: biodiversity_viewer_shiny_app
    access-groups: admins
    container-network: sp-example-net

logging:
  file:
    shinyproxy.log