
FROM antonbiatov/base_gbifwiever_datadamp_creator

RUN dnf install -y glibc-langpack-uk &&  \
    dnf install -y mc

ENV FUNCTION_DIR="/app" 
ENV APP_DIR="${FUNCTION_DIR}/scripts" \
    INPUT_DATA_DIR="${FUNCTION_DIR}/data" \
    OUTPUT_DATA_DIR="${FUNCTION_DIR}/outputs" \
    TEMP_DATA_DIR="${FUNCTION_DIR}/temp" 

ENV LANG=uk_UA.UTF-8 \
    LANGUAGE=uk_UA:en \
    LC_ALL=uk_UA.UTF-8

WORKDIR ${FUNCTION_DIR}

COPY . .

# COPY scripts/2_get_gbif_data.R ${APP_DIR}/2_get_gbif_data.R
# COPY scripts/3_filtering_cleaning_attribution.R ${APP_DIR}/3_filtering_cleaning_attribution.R
# COPY scripts/config.R ${APP_DIR}/config.R
# COPY scripts/gbif_ini.R ${APP_DIR}/gbif_ini.R
# COPY scripts/execute.sh ${APP_DIR}/execute.sh

# CMD Rscript ${APP_DIR}myScript.R

CMD ["/bin/bash"]

# CMD ${APP_DIR}/execute.sh

# CMD Rscript ${APP_DIR}/3_filtering_cleaning_attribution.R

# CMD ["sh", "-c", "${APP_DIR}/execute.sh"]

